### ISSUE TITLE
Chart widths hardcoded at load time

### ISSUE THREAD

**Issue by roccivic** [buildtimetrend/dashboard#1]
Perhaps this is something that needs to be kicked upstream to Keen.io, but the charts appear to hardcode their widths when they are loaded. Thus giving an illusion of responsiveness without actually being responsive. Samples below.

Shrink-load-expand:
![image](https://cloud.githubusercontent.com/assets/1194964/12829762/b404f5fc-cb83-11e5-8a61-0ee26aec8e62.png)

Expand-load-shrink:
![image](https://cloud.githubusercontent.com/assets/1194964/12829806/f4c8e63e-cb83-11e5-82b6-614eb96373fd.png)

**Comment by ruleant** [comment]
Well spotted. :)
The width is hardcoded in the chart/metric definition. Not sure what it will do to the layout when it is not specified. Some testing is required.

**Comment by roccivic** [comment]
BTW, the demos on Keen.io appear to suffer from the same issue. That's why I said it might have to be reported upstream.

**Comment by dustinlarimer** [comment]
@ruleant @roccivic yes, Google Charts do not support fluid resizing like other charting libraries, so those widths will be fixed on initial load. The metrics appear to be doing the same, which can be resolved, if you would like to open an issue on the keen-js repo : )

**Comment by roccivic** [comment]
Done, thanks @dustinlarimer

**Comment by dustinlarimer** [comment]
@roccivic I took a quick look at your code, and it appears that you're setting fixed widths on your metrics. If you remove the `.width(###)` method, this should be resolved and the metrics will become responsive, by default.

**Comment by ruleant** [comment]
Thanks for the info, @dustinlarimer

I'll remove the fixed widths and see what the effect is on the layout.

**Comment by ruleant** [comment]
@roccivic Fixed the issue with the widths of the metrics

**Comment by roccivic** [comment]
@ruleant That's great, thanks :)

**Comment by dustinlarimer** [comment]
:+1: awesome
